package eu.itcrafters.recipeapp.persistence.mapper;

import eu.itcrafters.recipeapp.controller.dto.RecipeDTO;
import eu.itcrafters.recipeapp.controller.dto.CreateRecipeRequest;
import eu.itcrafters.recipeapp.controller.dto.UpdateRecipeRequest;
import eu.itcrafters.recipeapp.persistence.recipe.Recipe;
import eu.itcrafters.recipeapp.persistence.category.Category;
import org.springframework.stereotype.Component;

@Component
public class RecipeMapper {

    public RecipeDTO toDTO(Recipe recipe) {
        if (recipe == null) {
            return null;
        }

        RecipeDTO dto = new RecipeDTO();
        dto.setId(recipe.getId());
        dto.setTitle(recipe.getTitle());
        dto.setDescription(recipe.getDescription());
        dto.setInstructions(recipe.getInstructions());
        dto.setCuisine(recipe.getCuisine());
        dto.setCategoryId(recipe.getCategory() != null ? recipe.getCategory().getId() : null);
        dto.setCreatedAt(recipe.getCreatedAt());
        dto.setUpdatedAt(recipe.getUpdatedAt());

        return dto;
    }

    public Recipe toEntity(RecipeDTO dto) {
        if (dto == null) {
            return null;
        }

        Recipe recipe = new Recipe();
        // Don't set ID for new entities - let JPA auto-generate it
        // recipe.setId(dto.getId());
        recipe.setTitle(dto.getTitle());
        recipe.setDescription(dto.getDescription());
        recipe.setInstructions(dto.getInstructions());
        recipe.setCuisine(dto.getCuisine());
        recipe.setCreatedAt(dto.getCreatedAt());
        recipe.setUpdatedAt(dto.getUpdatedAt());

        return recipe;
    }

    public RecipeDTO fromCreateRequest(CreateRecipeRequest request) {
        if (request == null) {
            return null;
        }

        RecipeDTO dto = new RecipeDTO();
        dto.setTitle(request.getTitle());
        dto.setDescription(request.getDescription());
        dto.setInstructions(request.getInstructions());
        dto.setCuisine(request.getCuisine());
        dto.setCategoryId(request.getCategoryId());
        // createdAt and updatedAt will be set in service layer
        // id will be auto-generated by JPA

        return dto;
    }

    public RecipeDTO fromUpdateRequest(UpdateRecipeRequest request) {
        if (request == null) {
            return null;
        }

        RecipeDTO dto = new RecipeDTO();
        dto.setTitle(request.getTitle());
        dto.setDescription(request.getDescription());
        dto.setInstructions(request.getInstructions());
        dto.setCuisine(request.getCuisine());
        dto.setCategoryId(request.getCategoryId());
        // createdAt and updatedAt will be set in service layer
        // id will be set from path variable

        return dto;
    }
}
